sudo: required
dist: trusty
language: php
php:
  - 7.1
  - 7.0
install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php artisan serve &
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - php artisan dusk
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - ./tests/Browser/screenshots/base64.bash
