language: php
php:
  - nightly
  - 7.0
install:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
