sudo: required
dist: trusty
language: php
env:
  - APP_ENV=testing
php:
  - 7.1
  - 7.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
install:
  - composer install
  - cp .env.travis .env
  - php artisan key:generate
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php -S localhost:8943 ./tests/docker/MockApi/srv/index.php > /dev/null 2>&1 &
    - php artisan serve > /dev/null 2>&1 &
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - php artisan dusk
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - ./tests/Browser/screenshots/upload-to-imgur.bash
